name: Release Packaging

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: "always"

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - run: just fmt

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - run: just test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        with:
          output-dir: dist

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl